### ISSUE TITLE
backpressure

### ISSUE THREAD

**Issue by Uzlopak** [Soontao/odata-v4-server#182]
Hi, 

you have a nice fork!

We encountered an backpressure issue in the original jaystack implementation, as the response-stream of express was not handled properly. Our microservice ran heavily into memory issues, as the mongodb was unloading its payload non-stop.

Your code seems to have the same issue. 

You have to change in request.ts the processor.on('data'...) in line 56 with

```
      processor.on('data', (chunk, encoding, done) => {
        if (!hasError) {
            if (!res.write(chunk, encoding, done)) {
                processor.pause();
            }
        }
      });

      res.on("drain", function () {
        processor.resume();
    });
```

**Comment by Uzlopak** [comment]
Opened PR #183

**Comment by Soontao** [comment]
Hello @Uzlopak 

Thanks for your contribution, sorry for my late reply, I'm busy on my company work before days.

PR has been merged.

BR.
