### ISSUE TITLE
$batch support multipart/mixed

### ISSUE THREAD

**Issue by ivanlynch** [Soontao/odata-v4-server#187]
Hi, how are you?

I've created a simple server, but when i try to consume it from OpenUI5 i get an error:

```
{
    "error": {
        "code": 415,
        "message": "Unsupported media type."
    }
}
```

1. I saw that right now is only support in json format and my question is: Have you planned to add this feature?
2. Can you suggest any workaround?

Regards,
Iván Lynch

**Comment by Soontao** [comment]
Hello @ivanlynch 

Sorry for my late reply, current `odata-v4-server` is not supported the `multipart` $batch operation of odata, its only support the OData V4.01 json format batch.

1. Not planned before, and no plan, multipart parsing/format is not easy for client/server, `odata-v4-server` will not implement it in design.
2. In a short words, if you want to get a odata server with `multipart` $batch with nodejs (and UI5), just try [SAP CAP framework](https://github.com/SAP-samples/cloud-cap-samples)

Thanks
