### ISSUE TITLE
enforce https

### ISSUE THREAD

**Issue by Uzlopak** [Soontao/odata-v4-server#219]
Hi,

we use our own fork of the odata server. Mainly because of we want to have the ability to enforce tls/https. Can you implement this in your Fork too?

https://github.com/Cognigy/odata-v4-server/commit/8814aec1861568af8e444766be1784f11bdbf0c8

**Comment by Soontao** [comment]
Hello @Uzlopak 

Firstly, sorry for my late reply, 

In fact, I'm not sure what's your question in fact, the `ctx.protocol` is only used for getting the `context url` for odata response.

If you want to make sure your server response `context` with `https` prefix, just ref this [demo](https://github.com/Soontao/odata-v4-server-demo/blob/master/src/server.ts)

```ts

    const port = parseInt(process.env.PORT || '50000', 10);

    const server = await createTypedODataServer({
        name: 'default',
        type: 'sqljs',
        synchronize: true,
        logging: true,
        cache: true,
        entities: [...SchoolEntities, ...ProposalEntities]
    });

    const app = express();

    app.set('trust proxy', true);

    app.use(server.create());

    app.listen(port, () => {
        console.log(`server started at ${port}`);
    });

```

focus on this line

```ts
app.set('trust proxy', true);
```

it indicates server use the proxy server protocol/hostname for express runtime, and then the runtime will response correct protocol prefix in context url

try this one:

https://odata-v4-server-demo.herokuapp.com/Proposals

```json
{
  "@odata.context": "https://odata-v4-server-demo.herokuapp.com/$metadata#Proposals",
  "value": []
}
```


Thanks your contribution. :)
