### ISSUE TITLE
$Skip query option not working

### ISSUE THREAD

**Issue by danielkamin** [Soontao/odata-v4-server#340]
The $skip option is not woriking as a standalone option. I have used the demo heroku app:
https://odata-v4-server-demo.herokuapp.com/api-docs/
Filled it with some sample data just to test it. Response of:
![image](https://user-images.githubusercontent.com/44261726/120313853-d8269b80-c2da-11eb-9652-cc63f315c5f5.png)

is:
![image](https://user-images.githubusercontent.com/44261726/120314059-1de36400-c2db-11eb-9c6a-257f84e604aa.png)

$top option works well:
![image](https://user-images.githubusercontent.com/44261726/120314171-3ce1f600-c2db-11eb-9ac6-0bf9c1e39cae.png)
![image](https://user-images.githubusercontent.com/44261726/120314196-453a3100-c2db-11eb-800a-f6dad0b0544c.png)

but $skip does not work at all:
![image](https://user-images.githubusercontent.com/44261726/120314268-5a16c480-c2db-11eb-808e-449a124b5128.png)
![image](https://user-images.githubusercontent.com/44261726/120314300-63079600-c2db-11eb-8ef5-a3e474eaf331.png)

Is there something I am missing?

**Comment by Soontao** [comment]
Hello @danielkamin 

Thanks for your detail comments, yes, its a bug in fact, if you don't specify the `$top` value, the default `0` will be used in  sql `LIMIT` expression, as a result, the response will be empty.

just try the url `https://odata-v4-server-demo.herokuapp.com/Teachers?$skip=1&$top=1000` (with `$top` parameter with a fixed value`

this bug will be fixed in the next patch

Regards
Theo

**Comment by Soontao** [comment]
fixed, after 0.2.48 released

**Comment by danielkamin** [comment]
Thank you very much for this quick response and let alone this quick fix.
You are awesome.


pon., 7 cze 2021 o 13:19 Theo Sun ***@***.***> napisał(a):

**Comment by danielkamin** [comment]
Hello,
I have come onto problem with functions such as:

*contains,any,*
*tolower*
*startswith*
Is there existing support for these options or is there plan to support
them?

Sincerely,
Daniel K.

wt., 8 cze 2021 o 21:54 Daniel Kamiński ***@***.***>
napisał(a):

**Comment by Soontao** [comment]
Hi @danielkamin 

Sorry, we don't have the plan to implement the ` Canonical Functions` in the odata standard.

Regards,
Theo
