### ISSUE TITLE
When $expand is used the properties type is not used according the Entity definition

### ISSUE THREAD

**Issue by zpaulovics** [Soontao/odata-v4-server#74]
query: START TRANSACTION
query: select * from `provider` ;
query: select * from `proposal`  WHERE `proposal`.`providerId` = 3fa85f64-5717-4562-b3fc-2c963f66aaaa;
query: select * from `proposal`  WHERE `proposal`.`providerId` = 3fa85f64-5717-4562-b3fc-2c963f66afa6;
query failed: select * from `proposal`  WHERE `proposal`.`providerId` = 3fa85f64-5717-4562-b3fc-2c963f66aaaa;
error: { Error: ER_BAD_FIELD_ERROR: Unknown column '3fa85f64' in 'where clause'
    at Query.Sequence._packetToError (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:161:44)
    at step (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'3fa85f64\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'select * from `proposal`  WHERE `proposal`.`providerId` = 3fa85f64-5717-4562-b3fc-2c963f66aaaa;' }
query: ROLLBACK
query failed: select * from `proposal`  WHERE `proposal`.`providerId` = 3fa85f64-5717-4562-b3fc-2c963f66afa6;
error: { Error: ER_BAD_FIELD_ERROR: Unknown column '3fa85f64' in 'where clause'
    at Query.Sequence._packetToError (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:161:44)
    at step (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'3fa85f64\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'select * from `proposal`  WHERE `proposal`.`providerId` = 3fa85f64-5717-4562-b3fc-2c963f66afa6;' }

**Comment by Soontao** [comment]
Hello @zpaulovics,

I dont understand your description, maybe you are using the original https://github.com/jaystack/odata-v4-server, and write your own DB logic with mysql ?
The obviours error is the value '3fa85f64-5717-4562-b3fc-2c963f66afa6' is not wrapped with single-quote so that mysql recognize it as a table name. 
You can provide more information to get more help.

Thanks :)

**Comment by zpaulovics** [comment]
Hi,

It may be my luck of knowledge of Odata, but I am a beginner in this topic:-). First I really started my tutorials by the original https://github.com/jaystack/odata-v4-server. But I have find your repository and started to use it. **I like it, and appreciate your work!!!** My code is based on your demo (https://github.com/Soontao/odata-v4-server-demo). Please, find below the detailed information regarding this issue.

### From my package.json: 
 . . . 
  "dependencies": {
    "@newdash/newdash": "^5.13.0",
    "@odata/server": "^0.2.34",
    "express": "^4.17.1",
    "mysql": "^2.18.1",
    "reflect-metadata": "^0.1.13",
    "sql.js": "^1.3.0",
    "tslib": "^2.0.1"
  },
 . . .

### My server.ts:
import { createTypedODataServer, odata, TypedODataServer } from '@odata/server';
import 'reflect-metadata';
import { PctEntities } from './models';

const run = async () =>   {
    const server = await createTypedODataServer({
        name: 'pct',
        type: 'mysql',
        host: process.env.PCTDB_HOST || 'localhost',
        port: parseInt(process.env.PCTDB_PORT) || 3306,
        database: "pctdb",
        username: "pctuser",
        password: "************",
        charset: "UTF8_GENERAL_CI",

        synchronize: true,
        logging: "all",
        cache: true,
        entities: PctEntities
    }, ...PctEntities);

    odata.namespace('mekh_pct');
    const s = server.create("/v4",parseInt(process.env.ODATA_SERVER_PORT) || 3000);

    s.once(
        'listening',
        () => console.log(`server started at ${s.address()['address']}:${s.address()['port']}`)
    );
};

if (require.main == module) {
    run();
}

### May retlated entities:

- Provider.ts

import { BaseODataModel, Edm, ODataColumn, ODataModel, ODataNavigation, 
    UUIDKeyProperty, withEntitySetName} from '@odata/server';
import { Proposal } from './Proposal';

// indicate the entity set name for entity
@withEntitySetName('Providers')
@ODataModel()
export class Provider extends BaseODataModel {

    @Edm.Guid
    @ODataColumn({ primary: true, generated: "uuid" })
    id: string;

    @Edm.Unicode
    @ODataColumn({ charset: "Utf8", length: 72 })
    name: string;

    @ODataColumn({ length: 13 })
    tax_numver: string;

    @ODataNavigation({ type: 'OneToMany', entity: () => Proposal, targetForeignKey: 'providerId' })
    proposals: Proposal[];
}

- Proposal.ts

import {
    BaseODataModel, Edm, ODataColumn, ODataModel,
    ODataNavigation, withEntitySetName, odata,
    ODataAction, TransactionContext, EdmType
} from '@odata/server';
import { Provider } from './Provider';

// indicate the entity set name for entity
@withEntitySetName('Proposals')
@ODataModel()
export class Proposal extends BaseODataModel {

    @Edm.Guid
    @ODataColumn({ primary: true, generated: "uuid" })
    id: string;

    @Edm.Unicode
    @ODataColumn({ charset: "Utf8", length: 72 })
    name: string;

    @ODataColumn({ type: "enum", enum: ["high", "medium-high", "medium", "medium-low", "low"] })
    voltage_level: string;

    @ODataColumn({ type: "enum", enum: ["blank", "profiles", "controlled", "time-series"] })
    consumer_profile: string;

    @Edm.Decimal
    @Edm.Precision(12)
    @Edm.Scale(2)
    @ODataColumn({ type: "decimal", precision: 12, scale: 2  })
    energy_fee: number;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    funds: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    nogaranty: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    garanty: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    green: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    loyalty: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    online: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    yearly: boolean;

    @Edm.Boolean
    @Edm.DefaultValue(false)
    @ODataColumn()
    co2: boolean;

    @Edm.Date
    @ODataColumn({ type: "date" })
    start_date: string;

    @Edm.Date
    @Edm.Nullable
    @ODataColumn({ type: "date" })
    end_date: string;

    @Edm.Boolean
    @Edm.DefaultValue(true)
    @ODataColumn()
    isPublic: boolean;

    @Edm.Guid
    @ODataColumn({ nullable: true, generated: "uuid" })
    providerId: string;

    @ODataNavigation({ type: 'ManyToOne', entity: () => Provider, foreignKey: 'providerId' })
    provider: Provider;

}

Yes, you are right, the problem come from is the uuid value '3fa85f64-5717-4562-b3fc-2c963f66afa6' is not wrapped with single-quote.

**Comment by Soontao** [comment]
Hello @zpaulovics 

Please check a unit test case in this file, this case is test-passed for mysql db:

https://github.com/Soontao/odata-v4-server/blob/0bb22ed8b0a0647214737e519744c3ce661481be/test/type/relationship.spec.ts#L52-L95

I'll use your models to reproduce & get response back in several hours.

Thanks :)

**Comment by zpaulovics** [comment]
Hi,

Some addition information, it may help to identify the reason of the issue... Look at the differences for booleans, and dates!

Request URI: http://localhost:3000/v4/Proposals(672633f5-9df4-44fe-82aa-d35badcb2ed2)?$expand=provider

```
{
    "@odata.context": "http://localhost:3000/v4/$metadata#Proposals/$entity",
    "@odata.id": "http://localhost:3000/v4/Proposals(672633f5-9df4-44fe-82aa-d35badcb2ed2)",
    "@odata.editLink": "http://localhost:3000/v4/Proposals(672633f5-9df4-44fe-82aa-d35badcb2ed2)",
    "id": "672633f5-9df4-44fe-82aa-d35badcb2ed2",
    "name": "string",
    "voltage_level": "medium",
    "consumer_profile": "time-series",
    "energy_fee": "34.58",
    "funds": true,
    "nogaranty": false,
    "garanty": false,
    "green": true,
    "loyalty": false,
    "online": false,
    "yearly": true,
    "co2": true,
    "start_date": "2020-09-21",
    "end_date": "2020-09-30",
    "isPublic": true,
    "providerId": "0210496d-4c66-4531-b788-ae8d6da398be",
    "provider": {
        "@odata.id": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
        "@odata.editLink": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
        "id": "0210496d-4c66-4531-b788-ae8d6da398be",
        "name": "DÉDÁSZ",
        "tax_numver": "12345678-1-44"
    }
}
```

Request URI: http://localhost:3000/v4/Proposals?$expand=provider

```
{
    "@odata.context": "http://localhost:3000/v4/$metadata#Proposals",
    "value": [
        {
            "id": "672633f5-9df4-44fe-82aa-d35badcb2ed2",
            "name": "string",
            "voltage_level": "medium",
            "consumer_profile": "time-series",
            "energy_fee": "34.58",
            "funds": 1,
            "nogaranty": 0,
            "garanty": 0,
            "green": 1,
            "loyalty": 0,
            "online": 0,
            "yearly": 1,
            "co2": 1,
            "start_date": "2020-09-21T00:00:00.000Z",
            "end_date": "2020-09-30T00:00:00.000Z",
            "isPublic": 1,
            "providerId": "0210496d-4c66-4531-b788-ae8d6da398be",
            "provider": {
                "@odata.id": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
                "@odata.editLink": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
                "id": "0210496d-4c66-4531-b788-ae8d6da398be",
                "name": "DÉDÁSZ",
                "tax_numver": "12345678-1-44"
            }
        }
    ]
}
```

**Comment by Soontao** [comment]
issues: 

- [ ] native sql query in service.find, will not apply transformer of typeorm, so that response value return native database value (1/0,date)
- [ ] expand query raise error when not found
- [ ] @DateFormat decorator ? its not odata standard.

**Comment by Soontao** [comment]
> Hi,
> 
> Some addition information, it may help to identify the reason of the issue... Look at the differences for booleans, and dates!
> 
> Request URI: http://localhost:3000/v4/Proposals(672633f5-9df4-44fe-82aa-d35badcb2ed2)?$expand=provider
> 
> ```
> {
>     "@odata.context": "http://localhost:3000/v4/$metadata#Proposals/$entity",
>     "@odata.id": "http://localhost:3000/v4/Proposals(672633f5-9df4-44fe-82aa-d35badcb2ed2)",
>     "@odata.editLink": "http://localhost:3000/v4/Proposals(672633f5-9df4-44fe-82aa-d35badcb2ed2)",
>     "id": "672633f5-9df4-44fe-82aa-d35badcb2ed2",
>     "name": "string",
>     "voltage_level": "medium",
>     "consumer_profile": "time-series",
>     "energy_fee": "34.58",
>     "funds": true,
>     "nogaranty": false,
>     "garanty": false,
>     "green": true,
>     "loyalty": false,
>     "online": false,
>     "yearly": true,
>     "co2": true,
>     "start_date": "2020-09-21",
>     "end_date": "2020-09-30",
>     "isPublic": true,
>     "providerId": "0210496d-4c66-4531-b788-ae8d6da398be",
>     "provider": {
>         "@odata.id": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
>         "@odata.editLink": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
>         "id": "0210496d-4c66-4531-b788-ae8d6da398be",
>         "name": "DÉDÁSZ",
>         "tax_numver": "12345678-1-44"
>     }
> }
> ```
> 
> Request URI: http://localhost:3000/v4/Proposals?$expand=provider
> 
> ```
> {
>     "@odata.context": "http://localhost:3000/v4/$metadata#Proposals",
>     "value": [
>         {
>             "id": "672633f5-9df4-44fe-82aa-d35badcb2ed2",
>             "name": "string",
>             "voltage_level": "medium",
>             "consumer_profile": "time-series",
>             "energy_fee": "34.58",
>             "funds": 1,
>             "nogaranty": 0,
>             "garanty": 0,
>             "green": 1,
>             "loyalty": 0,
>             "online": 0,
>             "yearly": 1,
>             "co2": 1,
>             "start_date": "2020-09-21T00:00:00.000Z",
>             "end_date": "2020-09-30T00:00:00.000Z",
>             "isPublic": 1,
>             "providerId": "0210496d-4c66-4531-b788-ae8d6da398be",
>             "provider": {
>                 "@odata.id": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
>                 "@odata.editLink": "http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)",
>                 "id": "0210496d-4c66-4531-b788-ae8d6da398be",
>                 "name": "DÉDÁSZ",
>                 "tax_numver": "12345678-1-44"
>             }
>         }
>     ]
> }
> ```

**Comment by Soontao** [comment]
hi @zpaulovics 

I've released a new version `0.2.35` to fix the response in-consistence issue, just check following test case which works on mysql/pg/hana.

https://github.com/Soontao/odata-v4-server/blob/671acc5d2392d695f86898060d9c077c1e5b59f4/test/type/entity.spec.ts#L9-L55

comments:
* the `type` property of the decorator 'Property/ODataColumn' will automatically perform `Edm` decorators and appending information to the odata metadata, user do not need mannually use the `Edm` decorators again. (if not, it maybe will be a bug)
* the `Decimal` type will use 'string' in javascript & json, and use native column type in DB, because js & json will lost precision data. 

and, I can not reproduce the SQL issue in the first comment, could you provide a odata query link to trigger that, it will be helpful. :)

Thanks

**Comment by zpaulovics** [comment]
Hi, 

Thank you for the released a new version 0.2.35 to fix the response in-consistence issue. I will check it out soon.

### Request URI: 
http://localhost:3000/v4/Providers(0210496d-4c66-4531-b788-ae8d6da398be)?$expand=proposals

### Respand
```
{
    "error": {
        "code": 500,
        "message": "ER_BAD_FIELD_ERROR: Unknown column '0210496d' in 'where clause'"
    }
}
```
### Server logs
```
query: START TRANSACTION
query: SELECT `Provider`.`id` AS `Provider_id`, `Provider`.`name` AS `Provider_name`, `Provider`.`tax_numver` AS `Provider_tax_numver` FROM `provider` `Provider` WHERE `Provider`.`id` IN (?) -- PARAMETERS: ["0210496d-4c66-4531-b788-ae8d6da398be"]
query: select * from `proposal`  WHERE `proposal`.`providerId` = 0210496d-4c66-4531-b788-ae8d6da398be;
query failed: select * from `proposal`  WHERE `proposal`.`providerId` = 0210496d-4c66-4531-b788-ae8d6da398be;
error: Error: ER_BAD_FIELD_ERROR: Unknown column '0210496d' in 'where clause'
```

**Comment by Soontao** [comment]
Hi @zpaulovics, 

Thanks for your useful link, Yes, its a bug, and the root reason is the DB layer not process the 'Edm.Guid' correctly, so, as you know, the error occurred. 

I' still check the query result for other types, but now, in the new release `0.2.36`, the `Guid` key should be processed correctly.

https://github.com/Soontao/odata-v4-server/blob/15cd23b4a487722e992d9ea21a08388b3a1dd84f/test/type/relationship.spec.ts#L52-L100

Thanks for your contribution.

**Comment by zpaulovics** [comment]
Hi Theo,

1. I have upgraded my code according your new demo version. I like the you fietures.
2. I have carried out same test using my data on m new code. Every thing worked fine with the 0.2.39 so fare.

I think you can close this ticket, now I can not see any outstanding issue.

Thanks a lot, for your helps and respansiveness. I do really appreciate all of that! God work!
